spring:
  datasource:
     url: jdbc:h2:e:/h2_db_file/datajpa
#     url: jdbc:h2/~/datajpa
#     url: jdbc:h2:tcp://localhost/~/datajpa
     hikari:
      username: sa
      password:
     driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  data:
   web:
     pageable:
       default-page-size: 10
       max-page-size: 2000
logging:
  level:
    sql: debug

